import type { Metadata } from "next";
import { Inter, Cinzel, Cinzel_Decorative , Montserrat} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
// const cinzel = Cinzel({ subsets: ["latin"] });
// const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
